CREATE TABLE [dbo].[StockData]
(
    STOCK VARCHAR(20) NOT NULL,
    MARKET VARCHAR(20) NOT NULL,
    EXCHANGETIMEZONE VARCHAR(40) NOT NULL,
    CURRENCY VARCHAR(10) NOT NULL,
    MARKETSTATE VARCHAR(20) NOT NULl,
    REGULARMARKETPRICE DECIMAL(10, 3),
    REGULARMARKETTIME DATETIME,
    MARKETCAP VARCHAR(50) NOT NULl, 
    AVERAGEANALYSTRATING DECIMAL(10, 2),
    ANALYSTBUYSELL VARCHAR(10) NOT NULl, 
    MARKETCAPINTRILLION$$ VARCHAR(10) NOT NULl

)
WITH
(
    DISTRIBUTION = ROUND_ROBIN,
    CLUSTERED COLUMNSTORE INDEX
)
GO